### ISSUE TITLE
Broken API Docs link

### ISSUE THREAD

**Issue by mumispb** [bennypowers/stripe-elements#101]
Hey, everyone!

I think the URL for the API Docs of the library is not currently working. Does anyone have a basic implementation example that you could share?

**Comment by bennypowers** [comment]
Thanks for the issue

yes, this is because I recently updated my personal site.

in the mean time you can read the docs sources here [in this repo](https://github.com/bennypowers/stripe-elements/blob/main/docs/index.md)

**Comment by mumispb** [comment]
Thanks a lot!
