### ISSUE TITLE
`<stripe-payment-request>` not displaying anything?

### ISSUE THREAD

**Issue by baptisteArno** [bennypowers/stripe-elements#105]
Hi,

When rendering:

```tsx
<stripe-payment-request
        publishable-key={props.options.publicKey}
        generate="token"
        amount="326"
        label="Double Double"
        country="CA"
        currency="cad"
      >
        <stripe-display-item data-amount="125" data-label="Double Double" />
        <stripe-display-item data-amount="199" data-label="Box of 10 Timbits" />
      </stripe-payment-request>
```

It doesn't show anything. And there are no errors in console.

I'm not sure what `stripe-payment-request` is supposed to display, though! I wanted to try it out.

**Comment by bennypowers** [comment]
does the browser support payment request? check the readonly `canMakePayment` property or listen for `unsupported` event.

**Comment by baptisteArno** [comment]
Oh so `<stripe-payment-request>` is for https://stripe.com/docs/stripe-js/elements/payment-request-button?

Maybe it doesn't display because I'm testing on http://localhost

**Comment by bennypowers** [comment]
that's correct. you have to test it on https
