### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by timsayshey** [bennypowers/stripe-elements#109]
Heads up

![image](https://user-images.githubusercontent.com/1148940/216772156-d6896031-4f77-43a5-8dc5-4afd31ebb0f5.png)

**Comment by bennypowers** [comment]
#104 
#103 

PR to https://github.com/bennypowers/bennypowers.dev. maybe with a git submodule, or by telling 11ty to pull in the files in the build :shrug:
