### ISSUE TITLE
Warning about using lineHeight

### ISSUE THREAD

**Issue by phidias51** [bennypowers/stripe-elements#15]
I get the following warning about using lineHeight.

controller-83d5c0f16db3a3334e1d41f173fbe61f.js:1 The use of the style property lineHeight is discouraged, because it can lead to visual inconsistencies among various browsers. Consider using a padding on the Element’s container instead.

**Comment by bennypowers** [comment]
Can you give me a little more info?

**Comment by phidias51** [comment]
I put the stripe-elements element into my page, and the warning I described earlier appears in the console. I'm guessing that the lineHeight attribute that you have isn't encouraged: https://github.com/bennypowers/stripe-elements/blob/master/stripe-elements.html#L212

**Comment by bennypowers** [comment]
this should be handled by #17 will close now, please reopen if it becomes an issue with the lit-element version
