### ISSUE TITLE
Can't Style Error Message

### ISSUE THREAD

**Issue by phidias51** [bennypowers/stripe-elements#16]
I've been trying to style the error message, but I can't seem to get it to work. 

`
            stripe-element{
                --stripe-elements-invalid-color: white;
            }
`
This doesn't actually turn the error text white. Is there some other selector I should be using?

**Comment by bennypowers** [comment]
Try with the lit-element branch, should work. God-willing, I'll be publishing that on npm soon.

```
npm i git+ssh://git@github.com:bennypowers/stripe-elements.git#lit-element
```

Will close now, please reopen if you can reproduce on the lit-element branch.

<img width="515" alt="Screenshot 2019-03-25 02 53 15" src="https://user-images.githubusercontent.com/1466420/54888809-88a1e500-4eb1-11e9-8fc6-aa6fe3bb1a72.png">
