### ISSUE TITLE
undefned things in LitElement demos in storybook

### ISSUE THREAD

**Issue by btopro** [bennypowers/stripe-elements#37]
simple addition to the storybook doc
```js
import { ifDefined } from "lit-html/directives/if-defined.js";
import "@power-elements/json-viewer/json-viewer.js";
```

**Comment by bennypowers** [comment]
Hello Mr Ollendyke it's nice to see you here :D

You mean, I should add those lines to one of the codesandbox demos?

**Comment by bennypowers** [comment]
Can you tell me if https://github.com/bennypowers/stripe-elements/pull/39/files?short_path=d9ba6be#diff-d9ba6bea5dd398c95af0ac65a26fd27f does the trick?

**Comment by btopro** [comment]
yup that looks good
