### ISSUE TITLE
stripe-payment-request LitElement demo doesn't work like website

### ISSUE THREAD

**Issue by btopro** [bennypowers/stripe-elements#38]
Is there a requirement in local development that won't work without a cert perhaps? I've got my publishable key int he right place and it works in the `stripe-elements` demo.

The `<stripe-payment-request>` on the storybook actually opens up the `stripe-elements` demo

**Comment by bennypowers** [comment]
payment request api is only available on ssl sites. i haven't found a way to test it out other than deploying to a staging site. maybe a self-signed cert would work

**Comment by bennypowers** [comment]
If it's ok with you i'll close this. Reopen if you have some ideas how to make this work
