### ISSUE TITLE
the inbuilt submit method of stripe-element doesn't give back token object..

### ISSUE THREAD

**Issue by bipana50** [bennypowers/stripe-elements#45]
I am using it in polymer 3 component and the publishable key is not the problem. Doesn't return token but returns pending promise. Am I missing something? 

          <stripe-elements
              id="stripe"
              stripe-ready="{{ready}}"
              publishable-key="pk_test_......"
              token="{{token}}"
              error="{{error}}"
            ></stripe-elements>
    let stripeElement = this.shadowRoot.querySelector("#stripe");
    stripeElement.submit();

**Comment by bennypowers** [comment]
Hello and thanks for opening this issue.

It's hard to debug without seeing your code, do you have a reproduction you can share?

**Comment by bennypowers** [comment]
I created this example and it appears to work:

https://codesandbox.io/s/stripe-elements-web-component-polymer-uhyjn

You can base your reproduction off it

**Comment by bennypowers** [comment]
from the above codesandbox it looks like the token-changed event is not firing for some reason

**Comment by bipana50** [comment]
`import { PolymerElement, html } from "@polymer/polymer/polymer-element.js";
import "@vaadin/vaadin-text-field";
import "@polymer/iron-pages/iron-pages.js";
import "@polymer/paper-styles/shadow";
import "@polymer/paper-fab/paper-fab.js";
import { afterNextRender } from "@polymer/polymer/lib/utils/render-status.js";
import "@power-elements/stripe-elements";
import "@aspen-elements/aspen-icons/aspen-icons";

/**
 * `asp-credit-card` This component displays a credit card.
 *
 * @summary ShortDescription.
 * @customElement
 * @polymer
 * @extends {Polymer.Element}
 */
class AspCreditCard extends PolymerElement {
  static get template() {
    return html`
      <style>
        :host {
          display: block;
          --card-width: 400px;
          --label-color: rgba(200, 200, 200, 0.8);
        }
        .card {
          @apply --shadow-elevation-16dp;
          background-color: #252525;
          background-image: url("/images/wheat2.png");
          background-position-x: right;
          background-repeat: no-repeat;
          border-radius: 10px;
          height: 200px;
          width: var(--card-width);
          padding: 10px;
        }
        .content-initialized {
          position: relative;
          top: 80px;
          width: var(--card-width);
        }
        .content-not-initialized {
          position: relative;
          top: 40px;
        }
        vaadin-text-field {
          --lumo-secondary-text-color: var(--label-color);
          --lumo-contrast-10pct: white;
          width: 100%;
          font-size: 0.85em;
        }
        vaadin-text-field[focused] {
          --lumo-secondary-text-color: white;
        }
        .card-text {
          color: white;
        }
        #card-number {
          font-size: 1em;
        }
        .exp-line {
          @apply --layout-horizontal;
          font-size: 0.8em;
        }
        .exp-container {
          margin-top: 10px;
        }
        label {
          font-size: 0.8em;
          color: var(--label-color);
        }
        #card-type {
          font-size: 2em;
        }
        paper-button {
          height: 30px;
          background-color: rgb(249, 200, 40);
          text-transform: none;
        }
        .error-msg {
          font-size: 0.7em;
        }
        stripe-element {
          --stripe-elements-invalid-color: white;
        }

        paper-fab[is-visible] {
          background-color: rgb(249, 200, 40);
          color: black;
          position: relative;
          left: 80%;
          top: -20px;
          display: inline-block;
        }
        paper-fab {
          display: none;
        }
      </style>

      <div class="card">
        <iron-pages selected="{{selectedView}}" attr-for-selected="id">
          <div id="not-editable" class="content-initialized">
          
            <div id="card-type" class="card-text">
              [[cardModel.brand]]
            </div>
            <div id="card-number" class="card-text card-number">
              XXXX XXXX XXXX [[cardModel.last4]]
            </div>
            
            <div class="exp-container">
              <label>Expiration</label>
              <div class="exp-line">
                <div class="card-text">
                  [[cardModel.exp_month]] / [[cardModel.exp_year]]
                </div>
              </div>
            </div>
            
          </div>

          <div id="editable" class="content-not-initialized">
            <label>Card Details</label>
            <stripe-elements
              id="stripe"
              stripe-ready="{{ready}}"
              publishable-key="pk_test_hZXWxsk3yQ0ZZelSm7xpSLbM"
              token="{{token}}"
              error="{{error}}"
            ></stripe-elements>
            <paper-button raised on-tap="__saveCard">Save</paper-button>
          </div>
        </iron-pages>
      </div>
      <paper-fab
        is-visible$="[[isInitialized]]"
        icon="aspen:pencil"
        on-tap="__showEditableView"
      ></paper-fab>
    `;
  }
  /**
   * String providing the tag name to register the element under.
   */
  static get is() {
    return "asp-credit-card";
  }

  /**
   * Object describing property-related metadata used by Polymer features
   */
  static get properties() {
    return {
      /** The user object. */
      model: {
        type: Object,
        value: {}
      },

      /** The error message from Stripe. */
      error: {
        type: String,
        value: "",
        observer: "__handleError"
      },

      /** The model object returned by Stripe. */
      cardModel: {
        type: Object,
        computed: "__computeCardModel(model)"
      },

      /** The Stripe token (a structured object with multiple fields).*/
      token: {
        type: Object,
        value: null,
        observer: "__tokenChanged"
      },

      /** A flag that determines if the card information is valid. */
      isValid: {
        type: Boolean,
        notify: true,
        computed: "__computeIsValid(model)"
      },

      /** A flag that determiens if the card has been initialized. */
      isInitialized: {
        type: Boolean,
        computed: "__computeIsInitialized(model)",
        observer: "__updateSelectedView"
      },

      selectedView: {
        type: String,
        value: "editable"
      }
    };
  }

  __showEditableView() {
    this.set("selectedView", "editable");
  }

  __updateSelectedView(isInitialized) {
    let view = isInitialized ? "not-editable" : "editable";
    this.set("selectedView", view);
  }

  /**
   * Instance of the element is created/upgraded. Use: initializing state,
   * set up event listeners, create shadow dom.
   * @constructor
   */
  constructor() {
    super();
  }

  /**
   * Use for one-time configuration of your component after local DOM is initialized.
   */
  ready() {
    super.ready();

    afterNextRender(this, function() {});
  }

  /**
   * This method displays an error message generated when creating a card.
   * @param {String} error the error message.
   */

  __handleError(error) {
    if (error) {
      this.dispatchEvent(
        new CustomEvent("show-msg", {
          bubbles: true,
          composed: true,
          detail: {
            msg: error.message
          }
        })
      );
    }
  }

  /**
   * This method gets the card model once it has been initialized from Stripe.
   * @param {Object} model the user object model
   * @return {Object} the Stripe cardToken object, or an empty object if it has not been initialized.
   */

  __computeCardModel(model) {
    return model && model.card ? model.card : {};
  }

  /**
   * This method determines if the card object has been initialized by Stripe.
   * @param {Object} model the user object model
   * @return {Boolean} true if the cardToken object has been initialized
   */

  __computeIsInitialized(model) {
    return model && model.card;
  }

  /**
   * This method determines if the credit card data is valid and has been validated by Stripe.
   * @param {Object} model the credit card model
   */

  __computeIsValid(model) {
    let isValid = false;
    isValid = model && model.card;
    return isValid;
  }

  /**
   * This method adds a user subscription to the database.
   * @param {Event} e the event object
   */

  __saveCard(e) {
    console.log("hey from save card");
    let stripeElement = this.shadowRoot.querySelector("#stripe");
    // stripeElement.submit();
    stripeElement.createToken().then();
  }

  /**
   * This method updates the user's card token. The token is an object
   * returned by Stripe, which represents a valid credit card.
   * @param {Object} token the Stripe token object returned by the card.
   */

  __tokenChanged(token) {
    console.log("hey");
    debugger;
    if (token) {
      //this.set('model', token);
      this.set("selectedView", "not-editable");
      this.dispatchEvent(
        new CustomEvent("payment-source-created", {
          bubbles: true,
          composed: true,
          detail: {
            model: token
          }
        })
      );
      this.dispatchEvent(
        new CustomEvent("show-msg", {
          bubbles: true,
          composed: true,
          detail: {
            msg: "Card successfully created."
          }
        })
      );
    }
  }
}

window.customElements.define(AspCreditCard.is, AspCreditCard);`

**Comment by bipana50** [comment]
Hey, thank you for replying

**Comment by bennypowers** [comment]
I will investigate why the two-way binding isn't working for the `token` property

In the mean time, I suggest you use `on-token="onToken"` and `onToken({ detail: token }) { this.token = token; }` in the mean time

**Comment by bipana50** [comment]
I tried on-token attribute as you suggested and its working. Thank you.

**Comment by bennypowers** [comment]
> I tried on-token attribute as you suggested and its working. Thank you.

Glad to hear it.

Let's keep this issue open until I can release a fix for the two-way binding issue

**Comment by bipana50** [comment]
> > I tried on-token attribute as you suggested and its working. Thank you.
> 
> Glad to hear it.
> 
> Let's keep this issue open until I can release a fix for the two-way binding issue

Sounds good!

**Comment by bennypowers** [comment]
I've traced the bug to the `LitNotify` package, which I patch here in stripe-elements. It's only picking up on propertiess declared on the top-level class, but not the base class

**Comment by bennypowers** [comment]
Ok I think the root cause of this particular issue is that unpkg is importing the un-modified version of `@morbidick/lit-element-notify`

I'll send a PR

**Comment by bennypowers** [comment]
A solution that works with unpkg is waiting on https://github.com/morbidick/lit-element-notify/pull/16

**Comment by bipana50** [comment]
> A solution that works with unpkg is waiting on [morbidick/lit-element-notify#16](https://github.com/morbidick/lit-element-notify/pull/16)

Thank you and I will try to use the new version

**Comment by bennypowers** [comment]
version 2.3.5 fixes this finally

https://codesandbox.io/s/stripe-elements-web-component-polymer-uhyjn

Thanks again for the issue, @bipana50
