### ISSUE TITLE
Missing the important js code (urgent help needed)

### ISSUE THREAD

**Issue by bhtw** [bennypowers/stripe-elements#49]
Hi

Thanks for the great repository and hard work.
We are using Vue.js in our project and suddenly after a Vue upgrade stripe stopped working, just returns the error "Make sure the element is still mounted" when calling the function stripe.createPaymentMethod("card", this.cardName).
I contacted Stripe about the issue we have and they recommended your stripe-elements, so I have now spent days in re-implementing our stripe component using this stripe-elements.

The thing is, when I read your documentation of the [Vue framework implementation](https://bennypowers.dev/stripe-elements/?path=/docs/framework-examples-vue--stripe-elements), it lacks important code and examples.

It does not say how to import your project into the code, but I managed to import it by doing:
```js
<script>
  import stripeElements from "@power-elements/stripe-elements";
  
  export default {
  ...
  ...
  }
</script>
```

Further it does not contain working examples on other than the createToken() functionality.
I managed to get that working as well, but what we have previously implemented is the _paymentIntent_ and **createPaymentMethod**.

Reading your documentation regarding how to [create a paymentMethod](https://bennypowers.dev/stripe-elements/?path=/docs/elements-stripe-elements--generate-a-payment-method), the code example only contains the html part :-( 
What is also interesting of course is what is going on in the javascript part when you push the **Generate PaymentMethod** button.

When I follow your code example, this is how it looks like after some small changes, trying to fit the payment-method:
HTML part:
```html
<template>
  <article id="states">
    <stripe-elements
      ref="stripe"
      generate="payment-method"
      @change="onChange"
      @payment-method="onPaymentMethod"
      @error="onError"
      @ready="onReady"
      :publishable-key="publishableKey"
      icon-style="solid"
      show-error
      hide-postal-code
    ></stripe-elements>
  
   <button type="submit" class="btn-submit" @click.prevent="onClick">{{ payButtonText }}</button>

   </article>
</template>
```
Javascript part:
```js
<script>
  import stripeElements from "@power-elements/stripe-elements";

  export default {
    data() {
      return {
        publishableKey: ourPublicStripeKey,
        paymentMethod: null,
        error: null
        complete: false
      };
    },
    methods: {
      onChange({ target: { complete, empty } }) {
        this.complete = complete;
        this.empty = empty;
      },
      onError({ detail: error }) {
        this.error = error;
      },
      onPaymentMethod({ detail: paymentMethod }) {
        this.paymentMethod = paymentMethod;
        console.log("onPaymentMethod");
      },
      onClick() {
        this.$refs.stripe.createPaymentMethod("card", ????? );
      },
      .....
      .....
    }
  }
</script>
```

As you can see from the code I do not understand what to put as second parameter in the **createPaymentMethod()** call. Whatever I try putting in here which I think is related to the card element or whatever, I always seem to get the error response from Stripe:

> Please provide either an Element or PaymentMethod creation parameters to createPaymentMethod

Further reading in your documentation regarding the API attribute _element_ and _elements_ still gives me nothing due to lack of deeper description of exactly what it is, when and how to use it.

Could you please provide a fully working example of how to use the stripe.createPaymentMethod(), first of all for my case in a Vue framework, but I guess the same goes for the other frameworks as well. At least add the javascript logic around handling the different scenarios on your [Stripe Elements](https://bennypowers.dev/stripe-elements/?path=/docs/elements-stripe-elements--enter-a-publishable-key) chapter in your documentation.

**We are planning a release of our new software in a few weeks time**, but cannot do so before the Stripe payment procedure is working again, so please help me understand your <stripe-elements> and how to use it the best possible way. **This is urgent.** 

We would also love to see working examples on how to make an input form where the elements are split up in separate cardElement, expiryElement and cvcElement, if possible.

In advance, thanks.

**Comment by bennypowers** [comment]
> Hi

Hey :wave:

> Thanks for the great repository and hard work.

You know it :wink:

> We are using Vue.js in our project and suddenly after a Vue upgrade stripe stopped working, just returns the error "Make sure the element is still mounted" when calling the function stripe.createPaymentMethod("card", this.cardName).

Big OOF!

> I contacted Stripe about the issue we have and they recommended your stripe-elements

ORLY? :trollface: 

> ...when I read your documentation of the [Vue framework implementation](https://bennypowers.dev/stripe-elements/?path=/docs/framework-examples-vue--stripe-elements), it lacks important code and examples.
> 
> It does not say how to import your project into the code, but I managed to import it by doing:
> 
> ```js
> <script>
>   import stripeElements from "@power-elements/stripe-elements";
>   
>   export default {
>   ...
>   ...
>   }
> </script>
> ```

That'll work. if you don't need the reference to the class, you can just 
```js
import '@power-elements/stripe-elements';
```
You could also load it in html with 
```html
<script type="module" src="https://unpkg.com/@power-elements/stripe-elements?module"></script>
```

> Further it does not contain working examples on other than the createToken() functionality.
> I managed to get that working as well, but what we have previously implemented is the _paymentIntent_ and **createPaymentMethod**.

Here's a [working example](https://codesandbox.io/s/stripe-payment-request-web-component-vue-23edw?from-embed) that fires `payment-method`:
 
> Reading your documentation regarding how to [create a paymentMethod](https://bennypowers.dev/stripe-elements/?path=/docs/elements-stripe-elements--generate-a-payment-method), the code example only contains the html part :-(

Don't trash talk my fav programming language :wink:

> What is also interesting of course is what is going on in the javascript part when you push the **Generate PaymentMethod** button.

Due to Storybook's limitations (and my own stubbornness), the [code](https://github.com/bennypowers/stripe-elements/blob/39c4b03f5b8a718d1f8b84187f2bd211597cca73/stories/storybook-helpers.js#L181) that actually generates the token is abstracted away behind another component. I guess if you're only interested in JavaScript, then here's a JavaScript API for you:

```js
const element = document.querySelector('stripe-elements');
const paymentMethod = await element.submit();
```

You could also just call submit then listen for the `payment-method` event, whatever floats your ⛵️ .

> When I follow your code example, this is how it looks like after some small changes, trying to fit the payment-method:
> HTML part:
> 
> ```
> <template>
>   <article id="states">
>     <stripe-elements
>       ref="stripe"
>       generate="payment-method"
>       @change="onChange"
>       @payment-method="onPaymentMethod"
>       @error="onError"
>       @ready="onReady"
>       :publishable-key="publishableKey"
>       icon-style="solid"
>       show-error
>       hide-postal-code
>     ></stripe-elements>
>   
>    <button type="submit" class="btn-submit" @click.prevent="onClick">{{ payButtonText }}</button>
> 
>    </article>
> </template>
> ```
> 
> Javascript part:
> 
> ```js
> <script>
>   import stripeElements from "@power-elements/stripe-elements";
> 
>   export default {
>     data() {
>       return {
>         publishableKey: ourPublicStripeKey,
>         paymentMethod: null,
>         error: null
>         complete: false
>       };
>     },
>     methods: {
>       onChange({ target: { complete, empty } }) {
>         this.complete = complete;
>         this.empty = empty;
>       },
>       onError({ detail: error }) {
>         this.error = error;
>       },
>       onPaymentMethod({ detail: paymentMethod }) {
>         this.paymentMethod = paymentMethod;
>         console.log("onPaymentMethod");
>       },
>       onClick() {
>         // this.$refs.stripe.createPaymentMethod("card", ????? );
>         this.$refs.stripe.submit();
>       },
>       .....
>       .....
>     }
>   }
> </script>
> ```

FTFY.

> As you can see from the code I do not understand what to put as second parameter in the **createPaymentMethod()** call. Whatever I try putting in here which I think is related to the card element or whatever, I always seem to get the error response from Stripe:

IIRC it takes the same params as the Stripe SDK, but check the inline documentation for the method in the source code.

> > Please provide either an Element or PaymentMethod creation parameters to createPaymentMethod

Happy to take a PR

> Further reading in your documentation regarding the API attribute _element_ and _elements_ still gives me nothing due to lack of deeper description of exactly what it is, when and how to use it.

If it ain't broke, don't fix it.

> Could you please provide a fully working example of how to use the stripe.createPaymentMethod(), first of all for my case in a Vue framework, but I guess the same goes for the other frameworks as well. At least add the javascript logic around handling the different scenarios on your [Stripe Elements](https://bennypowers.dev/stripe-elements/?path=/docs/elements-stripe-elements--enter-a-publishable-key) chapter in your documentation.

Even happier to take a PR for these docs, but most users won't need this feature, as explained above. You can fork the codesandboxes as a starting point for each FW example.

> **We are planning a release of our new software in a few weeks time**, 

Mazel tov

> but cannot do so before the Stripe payment procedure is working again, so please help me understand your and how to use it the best possible way. **This is urgent.**

Hope this helped

> We would also love to see working examples on how to make an input form where the elements are split up in separate cardElement, expiryElement and cvcElement, if possible.

[example](https://codepen.io/pigd0g/pen/oNXbKzQ)

I'd be very interested to review a PR that adds slotted inputs for each of those fields.

> In advance, thanks.

Stay safe, stay home, and 💦 your 👐  for 20 seconds with plenty of soap.

**Comment by bhtw** [comment]
Wow!!
Thanks a lot for your quick response, man!!

I  will dive into your examples first thing in the morning, after a good night sleep - hopefully , thanks to you.

I will let you know as soon as I have gone through your suggestions and solutions and let you know when you can close this "issue".

Thanks !!

**Comment by bhtw** [comment]
Hi again.

I have been trying to understand your examples, but I cannot figure it out.
Could you please elaborate, but first, let me try to explain in more detail about my problem.


In our system, the users must be able to input their credit card details manually and have a button to press after accepting terms etc. So we cannot use the _stripe-payment-request_ method, if I have understood that method correctly, which rely on a browser supporting Payment Request API and already saved credit cards existing in the browser etc...

We also have splitted elements.

Following Stripe documentation we have implemented it like this:

Stripe is of cource loaded in the index.html file:
```html
<script src="https://js.stripe.com/v3/"></script>
```
In our form Vue.js component:

```js
<form>
  <label>{{ config.cardNumberLabel }}</label>
  <div ref="cardNumberElement" class="input empty"></div>
  <div class="small_fields">
    <div class="row">
      <label>{{ config.expirationDateLabel }}</label>
      <div ref="cardExpiryElement" class="input empty" placeholder="Expiry date"></div>
    </div>
    <div class="row">
      <label>{{ config.cvcLabel }}</label>
      <div ref="cardCvcElement" class="input empty"></div>
    </div>
  </div>
  <div id="card-errors" role="alert" v-if="formerror">{{formerror.message}}</div>
  <div class="input-fields">
    <app-terms id="appTerms"></app-terms>
  </div>

  <button type="submit" class="btn-submit" :disabled="!isFormValid()" @click.prevent="submitPayment">{{ payButtonText }}</button>
</form>
```

Inside the Vue.js _mounted()_ lifecycle hook we do the elements creation:
```js
mounted() {
      this.debugStripeLoaded();
      // Create Stripe elements and mount to html
      this.stripe = Stripe(this.config.stripeKey);
      this.elements = this.stripe.elements();

      this.cardNumber = this.elements.create("cardNumber", {
        style: this.elementStyles,
        classes: this.elementClasses,
        placeholder: this.config.cardNumberPlaceholder
      });
      this.cardNumber.mount(this.$refs.cardNumberElement);
      this.cardExpiry = this.elements.create("cardExpiry", {
        style: this.elementStyles,
        classes: this.elementClasses,
        placeholder: this.config.expirationDatePlaceholder
      });
      this.cardExpiry.mount(this.$refs.cardExpiryElement);
      this.cardCvc = this.elements.create("cardCvc", {
        style: this.elementStyles,
        classes: this.elementClasses,
        placeholder: this.config.cvcPlaceholder
      });
      this.cardCvc.mount(this.$refs.cardCvcElement);

      // Add event listeners on input change
      this.cardNumber.addEventListener("change", event => {
        this.formComplete.cardnumber = event.complete;
        this.cardError(event);
      });
      this.cardExpiry.addEventListener("change", event => {
        this.formComplete.expiry = event.complete;
        this.cardError(event);
      });
      this.cardCvc.addEventListener("change", event => {
        this.formComplete.cvc = event.complete;
        this.cardError(event);
      });
    }
```

The method used when the form is complete/valid uses the stripe paymentMethod function, as described in [Stripe documentation](https://stripe.com/docs/js/payment_methods/create_payment_method) and passes the cardNumber element as second parameter:

```js
async submitPayment() {
  const [err, response] = await to(
    this.stripe.createPaymentMethod("card", this.cardNumber)
  );
  if (err) {
    // handle error
  } else {
    // handle OK response
  }
```

And here comes the mystery, this has worked like a charm until lately, when Stripe returns the following error when the function is called:
> Please provide either an Element or PaymentMethod creation parameters to createPaymentMethod

So it seems to me, that _this.cardNumber_ suddenly looses its mounted parent element or something, since doing console.dir(this.cardNumber) and comparing it to another working version of the same implementation, _parent is _null_ when function returns error. The working version shows _parent => this.cardNumber element.

<hr>

Now, back to your _stripe-elements_ and what I am trying to achieve.

Using the below html with _stripe-elements_ and **not** _stripe-payment-request_

```html
<template>
  <article id="states">
    <stripe-elements
      ref="stripe"
      generate="payment-method"
      @change="onChange"
      @payment-method="onPaymentMethod"
      @error="onError"
      @ready="onReady"
      :publishable-key="publishableKey"
      icon-style="solid"
      show-error
      hide-postal-code
    ></stripe-elements>

   <button type="submit" class="btn-submit" @click.prevent="submitPayment">{{ payButtonText }}</button>

   </article>
</template>
```

In my understanding, your [working example](https://codesandbox.io/s/stripe-payment-request-web-component-vue-23edw?from-embed) is not using either _stripe-elements_ or contains a button.

If I have not misunderstood everything, **generate="payment-method"** should trigger a stripe.paymentMethod instead of a token, as according to [your documentation](https://bennypowers.dev/stripe-elements/?path=/docs/elements-stripe-elements--generate-a-payment-method), quote:

```html
<elements-demo label="Generate PaymentMethod">
  <stripe-elements generate="payment-method" publishable-key="${publishableKey}"> </stripe-elements>
</elements-demo>
```
Your **Generate Payment** button must perform the 
```
stripe.createPaymentMethod()
```
call in some way and provide the stripe-element as second parameter...no??

I'm sorry, but I did not understand how the code you provided can help me:
```js
const element = document.querySelector('stripe-elements');
const paymentMethod = await element.submit();
```
- How can I trigger the element.submit()?
- From where?

Please help me make a manual input of credit card details work with your stripe-elements, and paymentMethod working triggered by a button press.

And maybe, down the road, when your slots-implementation (issue #51) is ready, I can switch to separate elements again ....

Again, thanks a lot for your help. Really appreciate it.

**Comment by bennypowers** [comment]
If you just want to get a payment method, I already fixed your code. see above https://github.com/bennypowers/stripe-elements/issues/49#issuecomment-604034665

If you have to use your template with the split inputs, you'll need to call createPaymentMethod, You can do that several ways: either through the stripe-elements element's  `createPaymentMethod` method, in which case, the [documentation for all the element's methods are in the README for this repo](https://github.com/bennypowers/stripe-elements#methods) or you can call it directly on the element's `stripe` object, which is just a stripe instance. My documentation not withstanding, i'm just passing args to stripe, so for support in using that method, try `#stripe` on freenode.net irc.

As above I'm very happy to review a PR that adds the slotted input elements in, but until we can support that case, I can't really provide much more support for your project through this channel.

I'm going to close now because I've fixed the issue above. If you implement that fix and find it doesn't work, please open a new issue.

**Comment by bhtw** [comment]
Hi Benny

I figured it out eventually. So the answer from you that I was looking for could have been very simple, so I will add it here in case others are having the same trouble as I had.

1. Set the attribute _generate="payment-method"_ and listen for the payment-method response from stripe with _@payment-method="onPaymentMethod"_

```html
<stripe-elements
      ref="stripe"
      generate="payment-method"
      @change="onChange"
      @payment-method="onPaymentMethod"
      @error="onError"
      @ready="onReady"
      :publishable-key="publishableKey"
      show-error
    ></stripe-elements>

<button type="submit" class="btn-submit" :disabled="!isFormValid()" @click.prevent="onClick">{{ payButtonText }}</button>
```
2. In the onClick() method when button is clicked, get the generated paymentMethodData to use in the function call to Stripe. Successful response from Stripe triggers the _onPaymentMethod_ function call for further payment handling. Like so:
```js
methods: {
  onClick() {
    const paymentData = this.$refs.stripe.getPaymentMethodData();
    this.$refs.stripe.createPaymentMethod(paymentData);
  },
  onPaymentMethod({ detail: paymentMethod }) {
    console.dir(paymentMethod);
    // handle further actions of the payment, 
    // like sending paymentMethod.id to server side to generate PaymentMethodIntent etc..
    // handle SCA etc..
  },
  onError({ detail: error }) {
    this.error = error;
    console.log("onError");
  }
}
```
My error was that I manually tried to set the paymentData like I was before: 
```js
this.stripe.createPaymentMethod("card", this.cardNumber)
```
But using Stripes function _getPaymentMethodData()_ provides the object needed.

I hope this will help others.
