### ISSUE TITLE
Payment request not getting updated on re-renders

### ISSUE THREAD

**Issue by superchris** [bennypowers/stripe-elements#58]
Hello, I'm building a demo for some ecommerce custom elements and was attempting to use stripe-payment-request for the checkout. Everything works well if the `amount` attribute is set on the initial render. However, when the `amount` changes after a user adds an item to the cart, the payment request does not seem to get updated. When I click Pay Now I still see the previous value. I can see the amount getting correctly updated if I inspect the DOM.

Here is the relevant code from my app:

```typescript
render() {
    return html`
    <div class="c-table c-table--striped">
      <div class="c-table__caption">Cart</div>
      <div class="c-table__row c-table__row--heading">
        <span class="c-table__cell">Item</span>
        <span class="c-table__cell">Price</span>
      </div>
      ${this.cart && this.cart.map((item) => html`<stofrunt-cart-item .cartItem=${item}></stofrunt-cart-item>`)}
      <div class="c-table__row c-table__row--footer">Total: ${this.total}</div>
    </div>
    <stripe-payment-request
        publishable-key="${this.publishableKey}"
        generate="token"
        amount="${this.total}"
        label="Foo"
        country="US"
        currency="usd">
      ${this.cart && this.cart.map((item) => html`<stripe-display-item data-amount="${item.price}" data-label="${item.title}"></stripe-display-item>`)}
    </stripe-payment-request>
    `;
  }
```

**Comment by bennypowers** [comment]
Thanks for the issue @superchris I'm going to take a look at this just now

**Comment by superchris** [comment]
Thanks, I just checked and it works great!

**Comment by bennypowers** [comment]
Wonderful. Thanks again for the issue.
