### ISSUE TITLE
reset() not working

### ISSUE THREAD

**Issue by MrPhishfood** [bennypowers/stripe-elements#6]
Even when I wasn't using this element the clear() method has never worked for me. This is happening on Firefox and Chrome.

I tried `console.log(this._card.clear(), this._card.clear)`
and got this back in response:
`ƒ (){return this._checkDestroyed(),this._frame.clear(),this}`

So it looks like the function does exist but it just doesn't work. Can anyone confirm if this is working for them.

My current workaround is: to just unmount and mount it again:
```
this._card.unmount();
this._card.mount(this.$.card);
```

**Comment by bennypowers** [comment]
can you provide a jsbin reproduction?

**Comment by bennypowers** [comment]
Closing for now. @MrPhishfood please reopen if the issue persists for you.
