### ISSUE TITLE
Unable to integrate 

### ISSUE THREAD

**Issue by PrabhatLokwani** [bennypowers/stripe-elements#64]
Hi 
I was trying to implement the library for accepting payment but I am not able to understand the flow of how it works and which methods I have to call for getting payment methods and collecting response after successful payment or failure.

Does somebody has working example so that I can take some hint or If someone help me in figuring out how to implement this 

Please help me , I am stuck .
Thanks in Advance.

**Comment by bennypowers** [comment]
The stripe support channels are great for this. they have extensive docs and the chat room is really helpful

I'm going to close this now because it's related to stripe apis and not the the `<stripe-elements>` custom elements. good luck with your integration
