### ISSUE TITLE
Docs seem broken?

### ISSUE THREAD

**Issue by proimage** [bennypowers/stripe-elements#68]
Eg: https://bennypowers.dev/stripe-elements/?path=/docs/fallback-to-stripe-elements--enter-a-publishable-key

![image](https://user-images.githubusercontent.com/1027523/153478405-c800783a-f06d-4f6c-b03c-ad5374bee899.png)

**Comment by bennypowers** [comment]
This was solved in #67 which eschews storybook entirely in favour of good-old fashioned HTML.

I had some trouble with semantic release and haven't yet found the time to resolve it.

**Comment by bennypowers** [comment]
Closed in #71
