### ISSUE TITLE
doesn't working in Firefox

### ISSUE THREAD

**Issue by bboyrabi** [bennypowers/stripe-elements#8]
As you can see in the title, an error occurred trying to use this component with firefox.
The version of Firefox is 59.0.2 (64bit).
You can check with firefox, please see the [demo](https://www.webcomponents.org/element/bennypowers/stripe-elements/demo/demo/index.html).

Even if you enter Stripe publishable key, card number and press the 'GET TOKEN' button, you can not acquire the token.
Safari and chrome can be acquired normally.
Safari and chrome window.ShadyDOM is undefined.

Do you know the cause?

I am grateful for your work.
Thank you.

**Comment by bennypowers** [comment]
:wave: Hi there, and thanks for the issue!

Do you get any errors in the js console? Have you loaded the webcomponentsjs polyfill? (Which version?)

Can you try enabling web components support in Firefox settings and tell me if it works?

:Point_up: open `about:config` and set `dom.webcomponents.shadowdom.enabled` and `dom.webcomponents.customelements.enabled` to `true`

God willing, I'll be able to take a closer look after Passover.

**Comment by bboyrabi** [comment]
Thank you for your prompt reply.

> Do you get any errors in the js console?

No. Nothing was displayed. Only 'You may test your Stripe.js....must use HTTPS.' was abled to confirm.
handleError method catch an error. This error message is 'We could not retrieve data from the specified Element.\n Please make sure the Element you are attempting to use is still mounted.' but held by toast is 'OK'.
![2018-03-30 15 40 03](https://user-images.githubusercontent.com/9665307/38127341-bce48f4e-3430-11e8-9e73-0651e1a984af.png)


> Have you loaded the webcomponentsjs polyfill? (Which version?)

Yes. I am using Polymer2.0 and webcomponentsjs version is 1.1.0.

> Can you try enabling web components support in Firefox settings and tell me if it works?

I tried. But the screen collapsed and it could not be verified.

Thank you.

**Comment by bennypowers** [comment]
I investigated a little bit (with firefox' native implementation of web components enabled) and I was able to mount the card and generate a token. Although the demo page didn't look amazing, it did work both on the webcomponents.org demo page and locally.
