### ISSUE TITLE
Rollback to ES2019

### ISSUE THREAD

**Issue by k4lu-0p** [bennypowers/stripe-elements#88]
Hi @bennypowers ! My project uses ES2019 build. May you rollback to ES2019 build ? 

(e.g below of issue with chaining operator missing in ES2019)

![Screenshot 2022-06-08 at 14 15 26](https://user-images.githubusercontent.com/36934787/172717902-35705786-c6cb-4176-aeb9-5ab3f442a036.png)

**Comment by bennypowers** [comment]
Optional chaining and nullish coalescing are supported from node *14.5*. Current LTS is *16*. On the browser side, since Safari 13 and >20 Chrome and FF versions back.

**Comment by k4lu-0p** [comment]
> Optional chaining and nullish coalescing are supported from node _14.5_. Current LTS is _16_. On the browser side, since Safari 13 and >20 Chrome and FF versions back.

Sorry for the missing details. I use your components inside a Vue 2 project. ES2020 features is only available from Vue 3 and upgrade to the 3 version isn't the priority of my company 

https://stackoverflow.com/a/67282216

**Comment by bennypowers** [comment]
This is an issue with Vue
